# Generated by Django 4.0.4 on 2022-05-20 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppJuegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterField(
            model_name='jugador',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Hilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField()),
                ('fecha', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
