# Generated by Django 4.0.4 on 2022-05-20 14:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppJuegos', '0002_alter_jugador_options_alter_jugador_email_hilo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hilo',
            new_name='Post',
        ),
    ]
