# Generated by Django 4.0.4 on 2022-05-21 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0003_rename_hilo_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='consola',
            name='fechaLanzamiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consola',
            name='unidadesVendidas',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
