# Generated by Django 4.0.4 on 2022-05-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0004_consola_fechalanzamiento_consola_unidadesvendidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='precio',
            field=models.FloatField(),
        ),
    ]
