# Generated by Django 4.0.4 on 2022-05-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0005_alter_consola_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='compania',
            field=models.CharField(default='compañía', max_length=40),
        ),
        migrations.AlterField(
            model_name='juego',
            name='copiasCreadas',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='juego',
            name='fechaLanzamiento',
            field=models.DateField(default='01/01/1950'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='genero',
            field=models.CharField(default='juego', max_length=40),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cuerpo', models.TextField()),
                ('fechaComentario', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='AppJuegos.post')),
            ],
        ),
    ]
