# Generated by Django 4.0.4 on 2022-05-22 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppJuegos', '0005_alter_consola_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='compania',
            field=models.CharField(default='compañía', max_length=40),
        ),
        migrations.AlterField(
            model_name='juego',
            name='copiasCreadas',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='juego',
            name='fechaLanzamiento',
            field=models.DateField(default='01/01/1950'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='genero',
            field=models.CharField(default='juego', max_length=40),
        ),
       
    ]
