# Generated by Django 4.0.4 on 2022-05-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0006_alter_juego_compania_alter_juego_copiascreadas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
