# Generated by Django 4.0.4 on 2022-05-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0006_alter_juego_compania_alter_juego_copiascreadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
