# Generated by Django 4.0.4 on 2022-05-22 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppJuegos', '0006_alter_juego_compania_alter_juego_copiascreadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='nombre',
        ),
        migrations.AddField(
            model_name='jugador',
            name='avatar',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='jugador',
            name='user',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
