# Generated by Django 4.0.4 on 2022-05-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0012_delete_comentario'),
        ('AppJuegos', '0012_post_juego'),
    ]

    operations = [
    ]
