# Generated by Django 4.0.4 on 2022-05-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0013_merge_0012_delete_comentario_0012_post_juego'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jugador',
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(max_length=255),
        ),
    ]
