# Generated by Django 4.0.4 on 2022-05-29 01:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0015_alter_post_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
